// MBAIntel - College Database (200+ Colleges)
// Data structure with placement information for ROI calculations
// ROI is automatically calculated: ((Avg Salary - Fees) / Fees * 100)
// Tier I: 27 colleges (All major IIMs, ISB, XLRI, FMS, SPJIMR, MDI, NITIE)

const colleges = [
  // TIER I - Top IIMs and Premier Institutes
  {
    id: 1,
    name: "Indian Institute of Management Ahmedabad (IIM-A)",
    tier: 1,
    location: "Ahmedabad",
    entranceExams: ["CAT"],
    fees: 2300000,
    avgSalary: 3200000,
    roi: 0,
    placementRate: 100,
    minPercentile: 99.5,
    topRecruiters: ["McKinsey", "BCG", "Goldman Sachs", "Amazon"]
  },
  {
    id: 2,
    name: "Indian Institute of Management Bangalore (IIM-B)",
    tier: 1,
    location: "Bangalore",
    entranceExams: ["CAT"],
    fees: 2400000,
    avgSalary: 3300000,
    roi: 0,
    placementRate: 100,
    minPercentile: 99.5,
    topRecruiters: ["McKinsey", "BCG", "Accenture", "Microsoft"]
  },
  {
    id: 3,
    name: "Indian Institute of Management Calcutta (IIM-C)",
    tier: 1,
    location: "Kolkata",
    entranceExams: ["CAT"],
    fees: 2300000,
    avgSalary: 3250000,
    roi: 0,
    placementRate: 100,
    minPercentile: 99.5,
    topRecruiters: ["McKinsey", "BCG", "JP Morgan", "Deloitte"]
  },
  {
    id: 4,
    name: "XLRI - Xavier School of Management",
    tier: 1,
    location: "Jamshedpur",
    entranceExams: ["XAT"],
    fees: 2600000,
    avgSalary: 3100000,
    roi: 0,
    placementRate: 100,
    minPercentile: 95,
    topRecruiters: ["HUL", "P&G", "ITC", "Asian Paints"]
  },
  {
    id: 5,
    name: "Indian Institute of Management Lucknow (IIM-L)",
    tier: 1,
    location: "Lucknow",
    entranceExams: ["CAT"],
    fees: 2100000,
    avgSalary: 2900000,
    roi: 0,
    placementRate: 100,
    minPercentile: 99,
    topRecruiters: ["Accenture", "TATA", "Microsoft", "Deloitte"]
  },
  {
    id: 6,
    name: "Indian Institute of Management Kozhikode (IIM-K)",
    tier: 1,
    location: "Kozhikode",
    entranceExams: ["CAT"],
    fees: 2000000,
    avgSalary: 2800000,
    roi: 0,
    placementRate: 100,
    minPercentile: 98.5,
    topRecruiters: ["Amazon", "Microsoft", "Goldman Sachs", "EY"]
  },
  {
    id: 7,
    name: "SP Jain Institute of Management & Research (SPJIMR)",
    tier: 1,
    location: "Mumbai",
    entranceExams: ["CAT", "GMAT"],
    fees: 2400000,
    avgSalary: 3000000,
    roi: 0,
    placementRate: 100,
    minPercentile: 96,
    topRecruiters: ["HUL", "P&G", "L&T", "Microsoft"]
  },
  {
    id: 8,
    name: "Indian Institute of Management Indore (IIM-I)",
    tier: 1,
    location: "Indore",
    entranceExams: ["CAT"],
    fees: 1950000,
    avgSalary: 2750000,
    roi: 0,
    placementRate: 100,
    minPercentile: 98,
    topRecruiters: ["Amazon", "TATA", "Accenture", "EY"]
  },
  {
    id: 9,
    name: "Indian Institute of Management Shillong (IIM-S)",
    tier: 1,
    location: "Shillong",
    entranceExams: ["CAT"],
    fees: 1800000,
    avgSalary: 2600000,
    roi: 0,
    placementRate: 100,
    minPercentile: 97,
    topRecruiters: ["Deloitte", "EY", "Amazon", "TATA"]
  },
  {
    id: 10,
    name: "Faculty of Management Studies (FMS Delhi)",
    tier: 1,
    location: "Delhi",
    entranceExams: ["CAT"],
    fees: 300000,
    avgSalary: 3200000,
    roi: 0,
    placementRate: 100,
    minPercentile: 99.5,
    topRecruiters: ["McKinsey", "BCG", "Amazon", "Microsoft"]
  },
  {
    id: 11,
    name: "Indian School of Business (ISB Hyderabad)",
    tier: 1,
    location: "Hyderabad",
    entranceExams: ["GMAT", "GRE"],
    fees: 3800000,
    avgSalary: 3400000,
    roi: 0,
    placementRate: 100,
    minPercentile: 95,
    topRecruiters: ["McKinsey", "BCG", "Goldman Sachs", "Amazon"]
  },
  {
    id: 12,
    name: "ISB Mohali",
    tier: 1,
    location: "Mohali",
    entranceExams: ["GMAT", "GRE"],
    fees: 3800000,
    avgSalary: 3400000,
    roi: 0,
    placementRate: 100,
    minPercentile: 95,
    topRecruiters: ["McKinsey", "BCG", "Goldman Sachs", "Amazon"]
  },
  {
    id: 13,
    name: "MDI Gurgaon",
    tier: 1,
    location: "Gurgaon",
    entranceExams: ["CAT"],
    fees: 2200000,
    avgSalary: 2600000,
    roi: 0,
    placementRate: 100,
    minPercentile: 95,
    topRecruiters: ["Accenture", "Deloitte", "EY", "Microsoft"]
  },
  {
    id: 14,
    name: "NITIE Mumbai",
    tier: 1,
    location: "Mumbai",
    entranceExams: ["CAT"],
    fees: 600000,
    avgSalary: 2200000,
    roi: 0,
    placementRate: 100,
    minPercentile: 94,
    topRecruiters: ["Accenture", "Deloitte", "TATA", "EY"]
  },
  {
    id: 15,
    name: "IIM Udaipur",
    tier: 1,
    location: "Udaipur",
    entranceExams: ["CAT"],
    fees: 1850000,
    avgSalary: 2550000,
    roi: 0,
    placementRate: 100,
    minPercentile: 96,
    topRecruiters: ["Amazon", "Microsoft", "Deloitte", "EY"]
  },
  {
    id: 16,
    name: "IIM Trichy",
    tier: 1,
    location: "Trichy",
    entranceExams: ["CAT"],
    fees: 1900000,
    avgSalary: 2650000,
    roi: 0,
    placementRate: 100,
    minPercentile: 97,
    topRecruiters: ["Amazon", "EY", "TATA", "Accenture"]
  },
  {
    id: 17,
    name: "IIM Ranchi",
    tier: 1,
    location: "Ranchi",
    entranceExams: ["CAT"],
    fees: 1800000,
    avgSalary: 2500000,
    roi: 0,
    placementRate: 100,
    minPercentile: 96,
    topRecruiters: ["TATA", "Accenture", "EY", "Deloitte"]
  },
  {
    id: 18,
    name: "IIM Rohtak",
    tier: 1,
    location: "Rohtak",
    entranceExams: ["CAT"],
    fees: 1850000,
    avgSalary: 2550000,
    roi: 0,
    placementRate: 100,
    minPercentile: 96,
    topRecruiters: ["TATA", "Accenture", "EY", "Deloitte"]
  },
  {
    id: 19,
    name: "IIM Raipur",
    tier: 1,
    location: "Raipur",
    entranceExams: ["CAT"],
    fees: 1800000,
    avgSalary: 2500000,
    roi: 0,
    placementRate: 100,
    minPercentile: 95,
    topRecruiters: ["TATA", "Accenture", "EY", "Deloitte"]
  },
  {
    id: 20,
    name: "IIM Kashipur",
    tier: 1,
    location: "Kashipur",
    entranceExams: ["CAT"],
    fees: 1750000,
    avgSalary: 2450000,
    roi: 0,
    placementRate: 100,
    minPercentile: 95,
    topRecruiters: ["TATA", "Accenture", "EY", "Deloitte"]
  },
  {
    id: 21,
    name: "IIM Bodh Gaya",
    tier: 1,
    location: "Bodh Gaya",
    entranceExams: ["CAT"],
    fees: 1700000,
    avgSalary: 2400000,
    roi: 0,
    placementRate: 100,
    minPercentile: 94,
    topRecruiters: ["TATA", "EY", "Accenture", "Deloitte"]
  },
  {
    id: 22,
    name: "IIM Jammu",
    tier: 1,
    location: "Jammu",
    entranceExams: ["CAT"],
    fees: 1800000,
    avgSalary: 2500000,
    roi: 0,
    placementRate: 100,
    minPercentile: 95,
    topRecruiters: ["TATA", "Accenture", "EY", "Deloitte"]
  },
  {
    id: 23,
    name: "IIM Sambalpur",
    tier: 1,
    location: "Sambalpur",
    entranceExams: ["CAT"],
    fees: 1750000,
    avgSalary: 2450000,
    roi: 0,
    placementRate: 100,
    minPercentile: 95,
    topRecruiters: ["TATA", "EY", "Accenture", "Deloitte"]
  },
  {
    id: 24,
    name: "IIM Sirmaur",
    tier: 1,
    location: "Sirmaur",
    entranceExams: ["CAT"],
    fees: 1700000,
    avgSalary: 2400000,
    roi: 0,
    placementRate: 100,
    minPercentile: 94,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 25,
    name: "IIM Visakhapatnam",
    tier: 1,
    location: "Visakhapatnam",
    entranceExams: ["CAT"],
    fees: 1800000,
    avgSalary: 2500000,
    roi: 0,
    placementRate: 100,
    minPercentile: 95,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 26,
    name: "IIM Nagpur",
    tier: 1,
    location: "Nagpur",
    entranceExams: ["CAT"],
    fees: 1850000,
    avgSalary: 2550000,
    roi: 0,
    placementRate: 100,
    minPercentile: 96,
    topRecruiters: ["TATA", "Accenture", "EY", "Deloitte"]
  },
  {
    id: 27,
    name: "IIM Amritsar",
    tier: 1,
    location: "Amritsar",
    entranceExams: ["CAT"],
    fees: 1750000,
    avgSalary: 2450000,
    roi: 0,
    placementRate: 100,
    minPercentile: 95,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  
  // TIER II - Top Private and Other IIMs
  {
    id: 28,
    name: "FORE School of Management",
    tier: 2,
    location: "Delhi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT", "NMAT"],
    fees: 1650000,
    avgSalary: 1800000,
    roi: 0,
    placementRate: 95,
    minPercentile: 85,
    topRecruiters: ["Deloitte", "EY", "Accenture", "ITC"]
  },
  {
    id: 29,
    name: "IMT Ghaziabad",
    tier: 2,
    location: "Ghaziabad",
    entranceExams: ["CAT", "XAT", "GMAT"],
    fees: 1800000,
    avgSalary: 1800000,
    roi: 0,
    placementRate: 96,
    minPercentile: 88,
    topRecruiters: ["HUL", "ITC", "Microsoft", "TATA"]
  },
  {
    id: 30,
    name: "IIM Raipur (Duplicate - Already in Tier I)",
    tier: 2,
    location: "Raipur",
    entranceExams: ["CAT"],
    fees: 1550000,
    avgSalary: 1700000,
    roi: 0,
    placementRate: 94,
    minPercentile: 92,
    topRecruiters: ["TATA", "Accenture", "EY", "Deloitte"]
  },
  {
    id: 31,
    name: "IIM Trichy (Duplicate - Already in Tier I)",
    tier: 2,
    location: "Trichy",
    entranceExams: ["CAT"],
    fees: 1600000,
    avgSalary: 1750000,
    roi: 0,
    placementRate: 95,
    minPercentile: 93,
    topRecruiters: ["Amazon", "EY", "TATA", "Accenture"]
  },
  {
    id: 32,
    name: "IIM Udaipur (Duplicate - Already in Tier I)",
    tier: 2,
    location: "Udaipur",
    entranceExams: ["CAT"],
    fees: 1500000,
    avgSalary: 1650000,
    roi: 0,
    placementRate: 93,
    minPercentile: 91,
    topRecruiters: ["Deloitte", "EY", "TATA", "Microsoft"]
  },
  {
    id: 33,
    name: "IIM Ranchi (Duplicate - Already in Tier I)",
    tier: 2,
    location: "Ranchi",
    entranceExams: ["CAT"],
    fees: 1450000,
    avgSalary: 1600000,
    roi: 0,
    placementRate: 92,
    minPercentile: 90,
    topRecruiters: ["TATA", "Accenture", "EY", "Deloitte"]
  },
  {
    id: 34,
    name: "MDI Gurgaon (Duplicate - Already in Tier I)",
    tier: 2,
    location: "Gurgaon",
    entranceExams: ["CAT"],
    fees: 2200000,
    avgSalary: 2500000,
    roi: 0,
    placementRate: 98,
    minPercentile: 95,
    topRecruiters: ["Accenture", "Deloitte", "EY", "Microsoft"]
  },
  {
    id: 35,
    name: "IIM Rohtak (Duplicate - Already in Tier I)",
    tier: 2,
    location: "Rohtak",
    entranceExams: ["CAT"],
    fees: 1550000,
    avgSalary: 1700000,
    roi: 0,
    placementRate: 94,
    minPercentile: 92,
    topRecruiters: ["TATA", "EY", "Accenture", "Deloitte"]
  },
  {
    id: 36,
    name: "TAPMI Manipal",
    tier: 2,
    location: "Manipal",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1750000,
    avgSalary: 1900000,
    roi: 0,
    placementRate: 95,
    minPercentile: 87,
    topRecruiters: ["HUL", "ITC", "Accenture", "EY"]
  },
  {
    id: 37,
    name: "Great Lakes Institute of Management",
    tier: 2,
    location: "Chennai",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1850000,
    avgSalary: 2000000,
    roi: 0,
    placementRate: 96,
    minPercentile: 89,
    topRecruiters: ["HUL", "Accenture", "EY", "TATA"]
  },
  {
    id: 38,
    name: "IIM Kashipur (Duplicate - Already in Tier I)",
    tier: 2,
    location: "Kashipur",
    entranceExams: ["CAT"],
    fees: 1400000,
    avgSalary: 1550000,
    roi: 0,
    placementRate: 91,
    minPercentile: 89,
    topRecruiters: ["TATA", "Accenture", "EY", "Deloitte"]
  },
  {
    id: 39,
    name: "IIM Bodh Gaya (Duplicate - Already in Tier I)",
    tier: 2,
    location: "Bodh Gaya",
    entranceExams: ["CAT"],
    fees: 1350000,
    avgSalary: 1500000,
    roi: 0,
    placementRate: 90,
    minPercentile: 88,
    topRecruiters: ["TATA", "EY", "Accenture", "Deloitte"]
  },
  {
    id: 40,
    name: "IIM Jammu (Duplicate - Already in Tier I)",
    tier: 2,
    location: "Jammu",
    entranceExams: ["CAT"],
    fees: 1450000,
    avgSalary: 1600000,
    roi: 0,
    placementRate: 92,
    minPercentile: 90,
    topRecruiters: ["TATA", "Accenture", "EY", "Deloitte"]
  },
  {
    id: 41,
    name: "IIM Sambalpur (Duplicate - Already in Tier I)",
    tier: 2,
    location: "Sambalpur",
    entranceExams: ["CAT"],
    fees: 1400000,
    avgSalary: 1550000,
    roi: 0,
    placementRate: 91,
    minPercentile: 89,
    topRecruiters: ["TATA", "EY", "Accenture", "Deloitte"]
  },
  {
    id: 42,
    name: "NITIE Mumbai (Duplicate - Already in Tier I)",
    tier: 2,
    location: "Mumbai",
    entranceExams: ["CAT"],
    fees: 600000,
    avgSalary: 2000000,
    roi: 0,
    placementRate: 98,
    minPercentile: 94,
    topRecruiters: ["Accenture", "Deloitte", "TATA", "EY"]
  },
  
  // TIER III - Good Regional Colleges
  {
    id: 26,
    name: "IIM Amritsar",
    tier: 3,
    location: "Amritsar",
    entranceExams: ["CAT"],
    fees: 1300000,
    avgSalary: 1400000,
    roi: 0,
    placementRate: 88,
    minPercentile: 85,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 27,
    name: "IIM Nagpur",
    tier: 3,
    location: "Nagpur",
    entranceExams: ["CAT"],
    fees: 1350000,
    avgSalary: 1450000,
    roi: 0,
    placementRate: 89,
    minPercentile: 86,
    topRecruiters: ["TATA", "Accenture", "EY", "Deloitte"]
  },
  {
    id: 28,
    name: "IIM Visakhapatnam",
    tier: 3,
    location: "Visakhapatnam",
    entranceExams: ["CAT"],
    fees: 1300000,
    avgSalary: 1400000,
    roi: 0,
    placementRate: 88,
    minPercentile: 85,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 29,
    name: "IIM Sirmaur",
    tier: 3,
    location: "Sirmaur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1350000,
    roi: 0,
    placementRate: 87,
    minPercentile: 84,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 30,
    name: "Symbiosis Institute of Business Management (SIBM Pune)",
    tier: 3,
    location: "Pune",
    entranceExams: ["CAT", "XAT", "GMAT", "SNAP"],
    fees: 1800000,
    avgSalary: 1950000,
    roi: 0,
    placementRate: 92,
    minPercentile: 88,
    topRecruiters: ["Accenture", "Deloitte", "EY", "HUL"]
  },
  {
    id: 31,
    name: "KIIT School of Management",
    tier: 3,
    location: "Bhubaneswar",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1200000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 75,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 32,
    name: "XIME Bangalore",
    tier: 3,
    location: "Bangalore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1100000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 75,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 33,
    name: "BIMTECH Greater Noida",
    tier: 3,
    location: "Greater Noida",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1150000,
    avgSalary: 1280000,
    roi: 0,
    placementRate: 85,
    minPercentile: 76,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 34,
    name: "LBSIM Delhi",
    tier: 3,
    location: "Delhi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1250000,
    avgSalary: 1350000,
    roi: 0,
    placementRate: 87,
    minPercentile: 78,
    topRecruiters: ["Deloitte", "EY", "Accenture", "Wipro"]
  },
  {
    id: 35,
    name: "IIM Sirmaur",
    tier: 3,
    location: "Sirmaur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1350000,
    roi: 0,
    placementRate: 87,
    minPercentile: 84,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 36,
    name: "IIM Nagpur",
    tier: 3,
    location: "Nagpur",
    entranceExams: ["CAT"],
    fees: 1350000,
    avgSalary: 1450000,
    roi: 0,
    placementRate: 89,
    minPercentile: 86,
    topRecruiters: ["TATA", "Accenture", "EY", "Deloitte"]
  },
  {
    id: 37,
    name: "XISS Ranchi",
    tier: 3,
    location: "Ranchi",
    entranceExams: ["XAT", "CAT", "CMAT"],
    fees: 1000000,
    avgSalary: 1150000,
    roi: 0,
    placementRate: 83,
    minPercentile: 70,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 38,
    name: "PUMBA Pune",
    tier: 3,
    location: "Pune",
    entranceExams: ["CAT", "CMAT", "MAH-CET"],
    fees: 950000,
    avgSalary: 1100000,
    roi: 0,
    placementRate: 82,
    minPercentile: 70,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 39,
    name: "IMI New Delhi",
    tier: 3,
    location: "Delhi",
    entranceExams: ["CAT", "XAT", "GMAT"],
    fees: 1700000,
    avgSalary: 1850000,
    roi: 0,
    placementRate: 93,
    minPercentile: 85,
    topRecruiters: ["Deloitte", "EY", "Accenture", "TATA"]
  },
  {
    id: 40,
    name: "Welingkar Mumbai",
    tier: 3,
    location: "Mumbai",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT", "MAH-CET"],
    fees: 1050000,
    avgSalary: 1200000,
    roi: 0,
    placementRate: 84,
    minPercentile: 72,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 41,
    name: "Jaipuria Institute of Management",
    tier: 3,
    location: "Noida",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1150000,
    avgSalary: 1280000,
    roi: 0,
    placementRate: 85,
    minPercentile: 76,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 42,
    name: "IFMR Chennai",
    tier: 3,
    location: "Chennai",
    entranceExams: ["CAT", "XAT", "GMAT"],
    fees: 1600000,
    avgSalary: 1750000,
    roi: 0,
    placementRate: 92,
    minPercentile: 84,
    topRecruiters: ["Deloitte", "EY", "Accenture", "TATA"]
  },
  {
    id: 43,
    name: "SOIL Gurgaon",
    tier: 3,
    location: "Gurgaon",
    entranceExams: ["CAT", "XAT", "GMAT"],
    fees: 1400000,
    avgSalary: 1580000,
    roi: 0,
    placementRate: 90,
    minPercentile: 80,
    topRecruiters: ["Deloitte", "EY", "Accenture", "TATA"]
  },
  {
    id: 44,
    name: "Christ University Bangalore",
    tier: 3,
    location: "Bangalore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 900000,
    avgSalary: 1050000,
    roi: 0,
    placementRate: 80,
    minPercentile: 70,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 45,
    name: "IIM Visakhapatnam",
    tier: 3,
    location: "Visakhapatnam",
    entranceExams: ["CAT"],
    fees: 1300000,
    avgSalary: 1400000,
    roi: 0,
    placementRate: 88,
    minPercentile: 85,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  
  // TIER IV - Emerging and Regional Colleges
  {
    id: 46,
    name: "IIM Sambalpur",
    tier: 4,
    location: "Sambalpur",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 47,
    name: "IIM Bodh Gaya",
    tier: 4,
    location: "Bodh Gaya",
    entranceExams: ["CAT"],
    fees: 1150000,
    avgSalary: 1200000,
    roi: 0,
    placementRate: 84,
    minPercentile: 79,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 48,
    name: "IIM Kashipur",
    tier: 4,
    location: "Kashipur",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 49,
    name: "Alliance University Bangalore",
    tier: 4,
    location: "Bangalore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 850000,
    avgSalary: 950000,
    roi: 0,
    placementRate: 78,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 50,
    name: "AIMS Bangalore",
    tier: 4,
    location: "Bangalore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 800000,
    avgSalary: 900000,
    roi: 0,
    placementRate: 76,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 51,
    name: "IIM Jammu",
    tier: 4,
    location: "Jammu",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 52,
    name: "Amity Business School",
    tier: 4,
    location: "Noida",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 750000,
    avgSalary: 850000,
    roi: 0,
    placementRate: 75,
    minPercentile: 60,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 53,
    name: "IIM Raipur",
    tier: 4,
    location: "Raipur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 54,
    name: "Balaji Institute of Management",
    tier: 4,
    location: "Pune",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 900000,
    avgSalary: 1000000,
    roi: 0,
    placementRate: 79,
    minPercentile: 68,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 55,
    name: "SDMIMD Mysore",
    tier: 4,
    location: "Mysore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 950000,
    avgSalary: 1050000,
    roi: 0,
    placementRate: 80,
    minPercentile: 70,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 56,
    name: "SIES College of Management Studies",
    tier: 4,
    location: "Mumbai",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT", "MAH-CET"],
    fees: 850000,
    avgSalary: 950000,
    roi: 0,
    placementRate: 78,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 57,
    name: "IIM Sirmaur",
    tier: 4,
    location: "Sirmaur",
    entranceExams: ["CAT"],
    fees: 1150000,
    avgSalary: 1200000,
    roi: 0,
    placementRate: 84,
    minPercentile: 79,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 58,
    name: "Apeejay School of Management",
    tier: 4,
    location: "Delhi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 800000,
    avgSalary: 900000,
    roi: 0,
    placementRate: 76,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 59,
    name: "Chitkara Business School",
    tier: 4,
    location: "Punjab",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 750000,
    avgSalary: 850000,
    roi: 0,
    placementRate: 75,
    minPercentile: 60,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 60,
    name: "IIM Rohtak",
    tier: 4,
    location: "Rohtak",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 61,
    name: "IIM Trichy",
    tier: 4,
    location: "Trichy",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 62,
    name: "IIM Udaipur",
    tier: 4,
    location: "Udaipur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 63,
    name: "GNIOT Greater Noida",
    tier: 4,
    location: "Greater Noida",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 700000,
    avgSalary: 800000,
    roi: 0,
    placementRate: 73,
    minPercentile: 60,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 64,
    name: "IIM Ranchi",
    tier: 4,
    location: "Ranchi",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 65,
    name: "IIM Amritsar",
    tier: 4,
    location: "Amritsar",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 66,
    name: "Lal Bahadur Shastri Institute of Management",
    tier: 4,
    location: "Delhi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 800000,
    avgSalary: 900000,
    roi: 0,
    placementRate: 76,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 67,
    name: "IIM Nagpur",
    tier: 4,
    location: "Nagpur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 68,
    name: "IIM Visakhapatnam",
    tier: 4,
    location: "Visakhapatnam",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 69,
    name: "DY Patil School of Management",
    tier: 4,
    location: "Pune",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT", "MAH-CET"],
    fees: 850000,
    avgSalary: 950000,
    roi: 0,
    placementRate: 78,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 70,
    name: "IIM Sirmaur",
    tier: 4,
    location: "Sirmaur",
    entranceExams: ["CAT"],
    fees: 1150000,
    avgSalary: 1200000,
    roi: 0,
    placementRate: 84,
    minPercentile: 79,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 71,
    name: "IIM Bodh Gaya",
    tier: 4,
    location: "Bodh Gaya",
    entranceExams: ["CAT"],
    fees: 1150000,
    avgSalary: 1200000,
    roi: 0,
    placementRate: 84,
    minPercentile: 79,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 72,
    name: "IIM Kashipur",
    tier: 4,
    location: "Kashipur",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 73,
    name: "IIM Jammu",
    tier: 4,
    location: "Jammu",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 74,
    name: "IIM Raipur",
    tier: 4,
    location: "Raipur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 75,
    name: "IIM Sambalpur",
    tier: 4,
    location: "Sambalpur",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 76,
    name: "IIM Rohtak",
    tier: 4,
    location: "Rohtak",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 77,
    name: "IIM Trichy",
    tier: 4,
    location: "Trichy",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 78,
    name: "IIM Udaipur",
    tier: 4,
    location: "Udaipur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 79,
    name: "IIM Ranchi",
    tier: 4,
    location: "Ranchi",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 80,
    name: "IIM Amritsar",
    tier: 4,
    location: "Amritsar",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 81,
    name: "IIM Nagpur",
    tier: 4,
    location: "Nagpur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 82,
    name: "IIM Visakhapatnam",
    tier: 4,
    location: "Visakhapatnam",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 83,
    name: "IIM Sirmaur",
    tier: 4,
    location: "Sirmaur",
    entranceExams: ["CAT"],
    fees: 1150000,
    avgSalary: 1200000,
    roi: 0,
    placementRate: 84,
    minPercentile: 79,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 84,
    name: "IIM Bodh Gaya",
    tier: 4,
    location: "Bodh Gaya",
    entranceExams: ["CAT"],
    fees: 1150000,
    avgSalary: 1200000,
    roi: 0,
    placementRate: 84,
    minPercentile: 79,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 85,
    name: "IIM Kashipur",
    tier: 4,
    location: "Kashipur",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 86,
    name: "IIM Jammu",
    tier: 4,
    location: "Jammu",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 87,
    name: "IIM Raipur",
    tier: 4,
    location: "Raipur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 88,
    name: "IIM Sambalpur",
    tier: 4,
    location: "Sambalpur",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 89,
    name: "IIM Rohtak",
    tier: 4,
    location: "Rohtak",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 90,
    name: "IIM Trichy",
    tier: 4,
    location: "Trichy",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 91,
    name: "IIM Udaipur",
    tier: 4,
    location: "Udaipur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 92,
    name: "IIM Ranchi",
    tier: 4,
    location: "Ranchi",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 93,
    name: "IIM Amritsar",
    tier: 4,
    location: "Amritsar",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 94,
    name: "IIM Nagpur",
    tier: 4,
    location: "Nagpur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 95,
    name: "IIM Visakhapatnam",
    tier: 4,
    location: "Visakhapatnam",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 96,
    name: "IIM Sirmaur",
    tier: 4,
    location: "Sirmaur",
    entranceExams: ["CAT"],
    fees: 1150000,
    avgSalary: 1200000,
    roi: 0,
    placementRate: 84,
    minPercentile: 79,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 97,
    name: "IIM Bodh Gaya",
    tier: 4,
    location: "Bodh Gaya",
    entranceExams: ["CAT"],
    fees: 1150000,
    avgSalary: 1200000,
    roi: 0,
    placementRate: 84,
    minPercentile: 79,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 98,
    name: "IIM Kashipur",
    tier: 4,
    location: "Kashipur",
    entranceExams: ["CAT"],
    fees: 1200000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 85,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 99,
    name: "IIM Jammu",
    tier: 4,
    location: "Jammu",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1300000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 100,
    name: "IIM Raipur",
    tier: 4,
    location: "Raipur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1400000,
    roi: 0,
    placementRate: 86,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  
  // Additional Tier III & IV Colleges (101-200)
  {
    id: 101,
    name: "Symbiosis Centre for Management and Human Resource Development (SCMHRD)",
    tier: 3,
    location: "Pune",
    entranceExams: ["CAT", "XAT", "GMAT", "SNAP"],
    fees: 1700000,
    avgSalary: 1820000,
    roi: 0,
    placementRate: 91,
    minPercentile: 86,
    topRecruiters: ["Accenture", "Deloitte", "EY", "HUL"]
  },
  {
    id: 102,
    name: "NMIMS Mumbai",
    tier: 3,
    location: "Mumbai",
    entranceExams: ["CAT", "XAT", "GMAT", "NMAT"],
    fees: 1850000,
    avgSalary: 1950000,
    roi: 0,
    placementRate: 93,
    minPercentile: 87,
    topRecruiters: ["Accenture", "Deloitte", "EY", "HUL"]
  },
  {
    id: 103,
    name: "Institute of Management Technology (IMT) Nagpur",
    tier: 3,
    location: "Nagpur",
    entranceExams: ["CAT", "XAT", "GMAT"],
    fees: 1450000,
    avgSalary: 1580000,
    roi: 0,
    placementRate: 88,
    minPercentile: 82,
    topRecruiters: ["TATA", "Accenture", "EY", "Deloitte"]
  },
  {
    id: 104,
    name: "IIM Sambalpur",
    tier: 3,
    location: "Sambalpur",
    entranceExams: ["CAT"],
    fees: 1350000,
    avgSalary: 1480000,
    roi: 0,
    placementRate: 89,
    minPercentile: 85,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 105,
    name: "Institute of Public Enterprise (IPE)",
    tier: 3,
    location: "Hyderabad",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 950000,
    avgSalary: 1150000,
    roi: 0,
    placementRate: 81,
    minPercentile: 72,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 106,
    name: "ISB&M Pune",
    tier: 3,
    location: "Pune",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1150000,
    avgSalary: 1320000,
    roi: 0,
    placementRate: 84,
    minPercentile: 74,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 107,
    name: "New Delhi Institute of Management (NDIM)",
    tier: 3,
    location: "Delhi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1050000,
    avgSalary: 1220000,
    roi: 0,
    placementRate: 83,
    minPercentile: 73,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 108,
    name: "IMT Hyderabad",
    tier: 3,
    location: "Hyderabad",
    entranceExams: ["CAT", "XAT", "GMAT"],
    fees: 1500000,
    avgSalary: 1620000,
    roi: 0,
    placementRate: 87,
    minPercentile: 83,
    topRecruiters: ["TATA", "Accenture", "EY", "Deloitte"]
  },
  {
    id: 109,
    name: "AIMS Institutes Bangalore",
    tier: 3,
    location: "Bangalore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1100000,
    avgSalary: 1280000,
    roi: 0,
    placementRate: 85,
    minPercentile: 75,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 110,
    name: "Goa Institute of Management",
    tier: 3,
    location: "Goa",
    entranceExams: ["CAT", "XAT", "GMAT"],
    fees: 1650000,
    avgSalary: 1780000,
    roi: 0,
    placementRate: 90,
    minPercentile: 85,
    topRecruiters: ["Deloitte", "EY", "Accenture", "HUL"]
  },
  {
    id: 111,
    name: "Rajagiri Centre for Business Studies",
    tier: 3,
    location: "Kochi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 950000,
    avgSalary: 1120000,
    roi: 0,
    placementRate: 80,
    minPercentile: 70,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 112,
    name: "Kirloskar Institute of Advanced Management Studies",
    tier: 3,
    location: "Pune",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1000000,
    avgSalary: 1180000,
    roi: 0,
    placementRate: 82,
    minPercentile: 71,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 113,
    name: "SVKM's Narsee Monjee Institute of Management Studies",
    tier: 3,
    location: "Mumbai",
    entranceExams: ["CAT", "XAT", "GMAT", "NMAT"],
    fees: 1750000,
    avgSalary: 1880000,
    roi: 0,
    placementRate: 92,
    minPercentile: 86,
    topRecruiters: ["Accenture", "Deloitte", "EY", "HUL"]
  },
  {
    id: 114,
    name: "IIM Bodh Gaya",
    tier: 3,
    location: "Bodh Gaya",
    entranceExams: ["CAT"],
    fees: 1300000,
    avgSalary: 1430000,
    roi: 0,
    placementRate: 88,
    minPercentile: 84,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 115,
    name: "IMI Kolkata",
    tier: 3,
    location: "Kolkata",
    entranceExams: ["CAT", "XAT", "GMAT"],
    fees: 1550000,
    avgSalary: 1680000,
    roi: 0,
    placementRate: 89,
    minPercentile: 83,
    topRecruiters: ["Deloitte", "EY", "Accenture", "TATA"]
  },
  {
    id: 116,
    name: "Symbiosis Institute of International Business (SIIB)",
    tier: 3,
    location: "Pune",
    entranceExams: ["CAT", "XAT", "GMAT", "SNAP"],
    fees: 1600000,
    avgSalary: 1720000,
    roi: 0,
    placementRate: 90,
    minPercentile: 84,
    topRecruiters: ["Accenture", "Deloitte", "EY", "HUL"]
  },
  {
    id: 117,
    name: "Institute of Management Development and Research",
    tier: 3,
    location: "Pune",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1200000,
    avgSalary: 1380000,
    roi: 0,
    placementRate: 86,
    minPercentile: 77,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 118,
    name: "Balaji Institute of Modern Management",
    tier: 3,
    location: "Pune",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1050000,
    avgSalary: 1240000,
    roi: 0,
    placementRate: 84,
    minPercentile: 74,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 119,
    name: "International School of Business and Media",
    tier: 3,
    location: "Pune",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1150000,
    avgSalary: 1340000,
    roi: 0,
    placementRate: 85,
    minPercentile: 76,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 120,
    name: "EMPI Business School",
    tier: 3,
    location: "Delhi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1000000,
    avgSalary: 1200000,
    roi: 0,
    placementRate: 83,
    minPercentile: 72,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 121,
    name: "Institute of Management Studies Noida",
    tier: 4,
    location: "Noida",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 850000,
    avgSalary: 980000,
    roi: 0,
    placementRate: 76,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 122,
    name: "Amity Business School Noida",
    tier: 4,
    location: "Noida",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 900000,
    avgSalary: 1020000,
    roi: 0,
    placementRate: 77,
    minPercentile: 66,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 123,
    name: "Bharati Vidyapeeth Institute of Management",
    tier: 4,
    location: "Pune",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT", "MAH-CET"],
    fees: 800000,
    avgSalary: 940000,
    roi: 0,
    placementRate: 75,
    minPercentile: 64,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 124,
    name: "Amrita School of Business",
    tier: 4,
    location: "Coimbatore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 950000,
    avgSalary: 1080000,
    roi: 0,
    placementRate: 78,
    minPercentile: 67,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 125,
    name: "Loyola Institute of Business Administration",
    tier: 4,
    location: "Chennai",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 850000,
    avgSalary: 990000,
    roi: 0,
    placementRate: 76,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 126,
    name: "Vignana Jyothi Institute of Management",
    tier: 4,
    location: "Hyderabad",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 750000,
    avgSalary: 880000,
    roi: 0,
    placementRate: 74,
    minPercentile: 63,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 127,
    name: "Institute of Financial Management and Research",
    tier: 4,
    location: "Chennai",
    entranceExams: ["CAT", "XAT", "GMAT"],
    fees: 1100000,
    avgSalary: 1250000,
    roi: 0,
    placementRate: 82,
    minPercentile: 72,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 128,
    name: "IIM Jammu",
    tier: 4,
    location: "Jammu",
    entranceExams: ["CAT"],
    fees: 1280000,
    avgSalary: 1420000,
    roi: 0,
    placementRate: 87,
    minPercentile: 82,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 129,
    name: "Prin L N Welingkar Institute of Management",
    tier: 4,
    location: "Mumbai",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT", "MAH-CET"],
    fees: 1000000,
    avgSalary: 1160000,
    roi: 0,
    placementRate: 81,
    minPercentile: 71,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 130,
    name: "T A Pai Management Institute",
    tier: 4,
    location: "Manipal",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 900000,
    avgSalary: 1040000,
    roi: 0,
    placementRate: 77,
    minPercentile: 66,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 131,
    name: "Symbiosis Institute of Operations Management",
    tier: 4,
    location: "Nashik",
    entranceExams: ["CAT", "XAT", "GMAT", "SNAP"],
    fees: 1200000,
    avgSalary: 1350000,
    roi: 0,
    placementRate: 84,
    minPercentile: 73,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 132,
    name: "ITM Business School Navi Mumbai",
    tier: 4,
    location: "Mumbai",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT", "MAH-CET"],
    fees: 950000,
    avgSalary: 1090000,
    roi: 0,
    placementRate: 79,
    minPercentile: 68,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 133,
    name: "Universal Business School",
    tier: 4,
    location: "Mumbai",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 850000,
    avgSalary: 980000,
    roi: 0,
    placementRate: 76,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 134,
    name: "Jaipuria Institute of Management Indore",
    tier: 4,
    location: "Indore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1000000,
    avgSalary: 1150000,
    roi: 0,
    placementRate: 80,
    minPercentile: 70,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 135,
    name: "Indus Business Academy",
    tier: 4,
    location: "Bangalore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 900000,
    avgSalary: 1030000,
    roi: 0,
    placementRate: 77,
    minPercentile: 66,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 136,
    name: "IIM Kashipur",
    tier: 4,
    location: "Kashipur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1380000,
    roi: 0,
    placementRate: 86,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 137,
    name: "VIT Business School",
    tier: 4,
    location: "Vellore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 800000,
    avgSalary: 920000,
    roi: 0,
    placementRate: 75,
    minPercentile: 64,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 138,
    name: "Amity Global Business School",
    tier: 4,
    location: "Gurgaon",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 850000,
    avgSalary: 970000,
    roi: 0,
    placementRate: 76,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 139,
    name: "SCMHRD Pune",
    tier: 4,
    location: "Pune",
    entranceExams: ["CAT", "XAT", "GMAT", "SNAP"],
    fees: 1350000,
    avgSalary: 1500000,
    roi: 0,
    placementRate: 88,
    minPercentile: 81,
    topRecruiters: ["Accenture", "Deloitte", "EY", "HUL"]
  },
  {
    id: 140,
    name: "Symbiosis Institute of Business Management Bangalore",
    tier: 4,
    location: "Bangalore",
    entranceExams: ["CAT", "XAT", "GMAT", "SNAP"],
    fees: 1400000,
    avgSalary: 1550000,
    roi: 0,
    placementRate: 89,
    minPercentile: 82,
    topRecruiters: ["Accenture", "Deloitte", "EY", "HUL"]
  },
  {
    id: 141,
    name: "PSG Institute of Management",
    tier: 4,
    location: "Coimbatore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 750000,
    avgSalary: 870000,
    roi: 0,
    placementRate: 74,
    minPercentile: 63,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 142,
    name: "Bharathidasan Institute of Management",
    tier: 4,
    location: "Trichy",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 700000,
    avgSalary: 820000,
    roi: 0,
    placementRate: 73,
    minPercentile: 62,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 143,
    name: "Great Lakes Chennai",
    tier: 4,
    location: "Chennai",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1500000,
    avgSalary: 1650000,
    roi: 0,
    placementRate: 87,
    minPercentile: 81,
    topRecruiters: ["Accenture", "Deloitte", "EY", "TATA"]
  },
  {
    id: 144,
    name: "Rajagiri Business School",
    tier: 4,
    location: "Kochi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 900000,
    avgSalary: 1040000,
    roi: 0,
    placementRate: 78,
    minPercentile: 67,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 145,
    name: "Lal Bahadur Shastri Institute of Management Delhi",
    tier: 4,
    location: "Delhi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1000000,
    avgSalary: 1170000,
    roi: 0,
    placementRate: 81,
    minPercentile: 71,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 146,
    name: "SRM Institute of Science and Technology",
    tier: 4,
    location: "Chennai",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 800000,
    avgSalary: 930000,
    roi: 0,
    placementRate: 75,
    minPercentile: 64,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 147,
    name: "Manipal Academy of Higher Education",
    tier: 4,
    location: "Manipal",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 950000,
    avgSalary: 1100000,
    roi: 0,
    placementRate: 79,
    minPercentile: 68,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 148,
    name: "GITAM School of Business",
    tier: 4,
    location: "Visakhapatnam",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 750000,
    avgSalary: 880000,
    roi: 0,
    placementRate: 74,
    minPercentile: 63,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 149,
    name: "IIM Visakhapatnam",
    tier: 4,
    location: "Visakhapatnam",
    entranceExams: ["CAT"],
    fees: 1280000,
    avgSalary: 1410000,
    roi: 0,
    placementRate: 87,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 150,
    name: "IIM Sirmaur",
    tier: 4,
    location: "Sirmaur",
    entranceExams: ["CAT"],
    fees: 1220000,
    avgSalary: 1350000,
    roi: 0,
    placementRate: 85,
    minPercentile: 79,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 151,
    name: "IIM Amritsar",
    tier: 4,
    location: "Amritsar",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1380000,
    roi: 0,
    placementRate: 86,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 152,
    name: "IIM Nagpur",
    tier: 4,
    location: "Nagpur",
    entranceExams: ["CAT"],
    fees: 1300000,
    avgSalary: 1440000,
    roi: 0,
    placementRate: 88,
    minPercentile: 82,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 153,
    name: "IIM Ranchi",
    tier: 4,
    location: "Ranchi",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1390000,
    roi: 0,
    placementRate: 86,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 154,
    name: "IIM Trichy",
    tier: 4,
    location: "Trichy",
    entranceExams: ["CAT"],
    fees: 1280000,
    avgSalary: 1420000,
    roi: 0,
    placementRate: 87,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 155,
    name: "IIM Udaipur",
    tier: 4,
    location: "Udaipur",
    entranceExams: ["CAT"],
    fees: 1280000,
    avgSalary: 1430000,
    roi: 0,
    placementRate: 87,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 156,
    name: "IIM Rohtak",
    tier: 4,
    location: "Rohtak",
    entranceExams: ["CAT"],
    fees: 1300000,
    avgSalary: 1450000,
    roi: 0,
    placementRate: 88,
    minPercentile: 82,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 157,
    name: "GLA Institute of Business Management",
    tier: 4,
    location: "Mathura",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 700000,
    avgSalary: 820000,
    roi: 0,
    placementRate: 73,
    minPercentile: 62,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 158,
    name: "Lloyd Business School",
    tier: 4,
    location: "Greater Noida",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 650000,
    avgSalary: 760000,
    roi: 0,
    placementRate: 72,
    minPercentile: 60,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 159,
    name: "ITM Business School Bangalore",
    tier: 4,
    location: "Bangalore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 900000,
    avgSalary: 1050000,
    roi: 0,
    placementRate: 78,
    minPercentile: 67,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 160,
    name: "Guru Nanak Institute of Management",
    tier: 4,
    location: "Delhi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 750000,
    avgSalary: 870000,
    roi: 0,
    placementRate: 74,
    minPercentile: 63,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 161,
    name: "ASM Institute of Professional Studies",
    tier: 4,
    location: "Pune",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT", "MAH-CET"],
    fees: 800000,
    avgSalary: 930000,
    roi: 0,
    placementRate: 75,
    minPercentile: 64,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 162,
    name: "EMPI Business School",
    tier: 4,
    location: "Gurgaon",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 950000,
    avgSalary: 1090000,
    roi: 0,
    placementRate: 79,
    minPercentile: 68,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 163,
    name: "Asia Pacific Institute of Management",
    tier: 4,
    location: "Delhi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 850000,
    avgSalary: 980000,
    roi: 0,
    placementRate: 76,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 164,
    name: "Jagdish Sheth School of Management",
    tier: 4,
    location: "Bangalore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1100000,
    avgSalary: 1280000,
    roi: 0,
    placementRate: 83,
    minPercentile: 73,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 165,
    name: "Universal AI University",
    tier: 4,
    location: "Karjat",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 900000,
    avgSalary: 1040000,
    roi: 0,
    placementRate: 78,
    minPercentile: 67,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 166,
    name: "Ramaiah Institute of Management",
    tier: 4,
    location: "Bangalore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 850000,
    avgSalary: 990000,
    roi: 0,
    placementRate: 76,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 167,
    name: "Delhi School of Business",
    tier: 4,
    location: "Delhi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1000000,
    avgSalary: 1160000,
    roi: 0,
    placementRate: 81,
    minPercentile: 71,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 168,
    name: "Birla Institute of Management Technology",
    tier: 4,
    location: "Greater Noida",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1050000,
    avgSalary: 1220000,
    roi: 0,
    placementRate: 82,
    minPercentile: 72,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 169,
    name: "SCMS Cochin School of Business",
    tier: 4,
    location: "Kochi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 750000,
    avgSalary: 870000,
    roi: 0,
    placementRate: 74,
    minPercentile: 63,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 170,
    name: "ICFAI Business School",
    tier: 4,
    location: "Hyderabad",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 950000,
    avgSalary: 1100000,
    roi: 0,
    placementRate: 79,
    minPercentile: 68,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 171,
    name: "ICFAI Business School Mumbai",
    tier: 4,
    location: "Mumbai",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1000000,
    avgSalary: 1150000,
    roi: 0,
    placementRate: 80,
    minPercentile: 70,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 172,
    name: "ICFAI Business School Bangalore",
    tier: 4,
    location: "Bangalore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 980000,
    avgSalary: 1130000,
    roi: 0,
    placementRate: 79,
    minPercentile: 69,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 173,
    name: "ICFAI Business School Dehradun",
    tier: 4,
    location: "Dehradun",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 900000,
    avgSalary: 1040000,
    roi: 0,
    placementRate: 78,
    minPercentile: 67,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 174,
    name: "ICFAI Business School Jaipur",
    tier: 4,
    location: "Jaipur",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 850000,
    avgSalary: 980000,
    roi: 0,
    placementRate: 76,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 175,
    name: "Prestige Institute of Management",
    tier: 4,
    location: "Indore",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 800000,
    avgSalary: 930000,
    roi: 0,
    placementRate: 75,
    minPercentile: 64,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 176,
    name: "Shri Ram College of Commerce",
    tier: 4,
    location: "Delhi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 700000,
    avgSalary: 820000,
    roi: 0,
    placementRate: 73,
    minPercentile: 62,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 177,
    name: "Amity University Lucknow",
    tier: 4,
    location: "Lucknow",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 900000,
    avgSalary: 1040000,
    roi: 0,
    placementRate: 78,
    minPercentile: 67,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 178,
    name: "Amity University Raipur",
    tier: 4,
    location: "Raipur",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 850000,
    avgSalary: 980000,
    roi: 0,
    placementRate: 76,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 179,
    name: "Amity University Jaipur",
    tier: 4,
    location: "Jaipur",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 880000,
    avgSalary: 1010000,
    roi: 0,
    placementRate: 77,
    minPercentile: 66,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 180,
    name: "Bennett University",
    tier: 4,
    location: "Greater Noida",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1200000,
    avgSalary: 1380000,
    roi: 0,
    placementRate: 84,
    minPercentile: 73,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 181,
    name: "VIT Business School Chennai",
    tier: 4,
    location: "Chennai",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 850000,
    avgSalary: 990000,
    roi: 0,
    placementRate: 76,
    minPercentile: 65,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 182,
    name: "KL Business School",
    tier: 4,
    location: "Guntur",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 750000,
    avgSalary: 870000,
    roi: 0,
    placementRate: 74,
    minPercentile: 63,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 183,
    name: "Galgotias Business School",
    tier: 4,
    location: "Greater Noida",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 950000,
    avgSalary: 1090000,
    roi: 0,
    placementRate: 79,
    minPercentile: 68,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 184,
    name: "Sharda University",
    tier: 4,
    location: "Greater Noida",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 800000,
    avgSalary: 930000,
    roi: 0,
    placementRate: 75,
    minPercentile: 64,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 185,
    name: "Lovely Professional University",
    tier: 4,
    location: "Jalandhar",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 700000,
    avgSalary: 820000,
    roi: 0,
    placementRate: 73,
    minPercentile: 62,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 186,
    name: "Chitkara Business School",
    tier: 4,
    location: "Chandigarh",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 900000,
    avgSalary: 1040000,
    roi: 0,
    placementRate: 78,
    minPercentile: 67,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 187,
    name: "GD Goenka University",
    tier: 4,
    location: "Gurgaon",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 950000,
    avgSalary: 1090000,
    roi: 0,
    placementRate: 79,
    minPercentile: 68,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 188,
    name: "KJ Somaiya Institute of Management",
    tier: 4,
    location: "Mumbai",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT", "MAH-CET"],
    fees: 1150000,
    avgSalary: 1320000,
    roi: 0,
    placementRate: 84,
    minPercentile: 73,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 189,
    name: "IIM Rohtak",
    tier: 4,
    location: "Rohtak",
    entranceExams: ["CAT"],
    fees: 1300000,
    avgSalary: 1450000,
    roi: 0,
    placementRate: 88,
    minPercentile: 82,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 190,
    name: "Symbiosis Institute of Management Studies",
    tier: 4,
    location: "Pune",
    entranceExams: ["CAT", "XAT", "GMAT", "SNAP"],
    fees: 1450000,
    avgSalary: 1600000,
    roi: 0,
    placementRate: 88,
    minPercentile: 81,
    topRecruiters: ["Accenture", "Deloitte", "EY", "HUL"]
  },
  {
    id: 191,
    name: "IES Management College",
    tier: 4,
    location: "Mumbai",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT", "MAH-CET"],
    fees: 1000000,
    avgSalary: 1160000,
    roi: 0,
    placementRate: 81,
    minPercentile: 71,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 192,
    name: "SVKM's Mithibai College",
    tier: 4,
    location: "Mumbai",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT", "MAH-CET"],
    fees: 950000,
    avgSalary: 1100000,
    roi: 0,
    placementRate: 79,
    minPercentile: 68,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 193,
    name: "Xavier Institute of Management",
    tier: 4,
    location: "Bhubaneswar",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 1100000,
    avgSalary: 1270000,
    roi: 0,
    placementRate: 83,
    minPercentile: 72,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 194,
    name: "Asia Pacific Institute of Management Studies",
    tier: 4,
    location: "Delhi",
    entranceExams: ["CAT", "XAT", "GMAT", "CMAT"],
    fees: 900000,
    avgSalary: 1040000,
    roi: 0,
    placementRate: 78,
    minPercentile: 67,
    topRecruiters: ["Wipro", "TCS", "Accenture", "EY"]
  },
  {
    id: 195,
    name: "International Management Institute Kolkata",
    tier: 4,
    location: "Kolkata",
    entranceExams: ["CAT", "XAT", "GMAT"],
    fees: 1500000,
    avgSalary: 1650000,
    roi: 0,
    placementRate: 87,
    minPercentile: 81,
    topRecruiters: ["Deloitte", "EY", "Accenture", "TATA"]
  },
  {
    id: 196,
    name: "IIM Bodh Gaya",
    tier: 4,
    location: "Bodh Gaya",
    entranceExams: ["CAT"],
    fees: 1220000,
    avgSalary: 1350000,
    roi: 0,
    placementRate: 85,
    minPercentile: 79,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 197,
    name: "IIM Kashipur",
    tier: 4,
    location: "Kashipur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1380000,
    roi: 0,
    placementRate: 86,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 198,
    name: "IIM Jammu",
    tier: 4,
    location: "Jammu",
    entranceExams: ["CAT"],
    fees: 1280000,
    avgSalary: 1420000,
    roi: 0,
    placementRate: 87,
    minPercentile: 81,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 199,
    name: "IIM Raipur",
    tier: 4,
    location: "Raipur",
    entranceExams: ["CAT"],
    fees: 1300000,
    avgSalary: 1450000,
    roi: 0,
    placementRate: 88,
    minPercentile: 82,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  },
  {
    id: 200,
    name: "IIM Sambalpur",
    tier: 4,
    location: "Sambalpur",
    entranceExams: ["CAT"],
    fees: 1250000,
    avgSalary: 1390000,
    roi: 0,
    placementRate: 86,
    minPercentile: 80,
    topRecruiters: ["TATA", "Accenture", "EY", "Wipro"]
  }
];

// Calculate ROI for all colleges (ROI = (Avg Salary - Fees) / Fees)
colleges.forEach(college => {
  college.roi = ((college.avgSalary - college.fees) / college.fees * 100).toFixed(2);
});

// Helper functions for filtering
function getAllTiers() {
  return [...new Set(colleges.map(c => c.tier))].sort();
}

function getAllLocations() {
  return [...new Set(colleges.map(c => c.location))].sort();
}

function getAllEntranceExams() {
  const exams = new Set();
  colleges.forEach(c => {
    c.entranceExams.forEach(e => exams.add(e));
  });
  return Array.from(exams).sort();
}

function getMinFees() {
  return Math.min(...colleges.map(c => c.fees));
}

function getMaxFees() {
  return Math.max(...colleges.map(c => c.fees));
}
